# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bobamixer < Formula
  desc "CLI tool for managing multiple AI providers with intelligent routing and cost tracking"
  homepage "https://github.com/royisme/BobaMixer"
  version "2.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/royisme/BobaMixer/releases/download/v2.0.0/BobaMixer_darwin_amd64.tar.gz"
      sha256 "5135f6782adf7cd846cd6e3ec8ae6bbf4a89103661449c7b7a475bd6cf3282bd"

      def install
        bin.install "boba"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/royisme/BobaMixer/releases/download/v2.0.0/BobaMixer_darwin_arm64.tar.gz"
      sha256 "58d50da9a2197efce2d158c46dbe70d2d9f921ef67457580fd7e42e32567fdf0"

      def install
        bin.install "boba"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/royisme/BobaMixer/releases/download/v2.0.0/BobaMixer_linux_amd64.tar.gz"
      sha256 "5efd6793a19ba4c44b077c3d236ac0bda2ba78aa4a4f86d9ebe8c22b2de46350"
      def install
        bin.install "boba"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/royisme/BobaMixer/releases/download/v2.0.0/BobaMixer_linux_arm64.tar.gz"
      sha256 "0add292a1321282a727c36c6ef5874259ac0d0c8ed83d466f1ac7484ea198f72"
      def install
        bin.install "boba"
      end
    end
  end

  test do
    system "#{bin}/boba", "version"
  end
end
