# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Boba < Formula
  desc "CLI tool for managing multiple AI providers with intelligent routing and cost tracking"
  homepage "https://github.com/royisme/BobaMixer"
  version "1.0.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/royisme/BobaMixer/releases/download/v1.0.12/BobaMixer_darwin_amd64_v1.tar.gz"
      sha256 "9b3aa93c5a265407e0985be06c0b87ecd0eaca5885a46f4544821cea1349eb33"

      def install
        bin.install "boba"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/royisme/BobaMixer/releases/download/v1.0.12/BobaMixer_darwin_arm64_v8.0.tar.gz"
      sha256 "60401ee25502a6f832b39754985ccc2a227cde8524ba4e45f41d028a0cff6864"

      def install
        bin.install "boba"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/royisme/BobaMixer/releases/download/v1.0.12/BobaMixer_linux_amd64_v1.tar.gz"
      sha256 "e72b499105272ec8fc48810497065a0c3fa66cd31ddc794dbb0c6ba3b6e647a2"
      def install
        bin.install "boba"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/royisme/BobaMixer/releases/download/v1.0.12/BobaMixer_linux_arm64_v8.0.tar.gz"
      sha256 "9ceded67aaca27a2c9da26e5fa010fafde3cfd81a632fc3d3b12cede130b5bbd"
      def install
        bin.install "boba"
      end
    end
  end

  test do
    system "#{bin}/boba version"
  end
end
