# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bobamixer < Formula
  desc "CLI tool for managing multiple AI providers with intelligent routing and cost tracking"
  homepage "https://github.com/royisme/BobaMixer"
  version "1.0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/royisme/BobaMixer/releases/download/v1.0.6/BobaMixer_darwin_amd64.tar.gz"
      sha256 "e60624da6eab1f5dde9a903e272e8253bfd6a592ea892aeda8745a87b52bea55"

      def install
        bin.install "boba"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/royisme/BobaMixer/releases/download/v1.0.6/BobaMixer_darwin_arm64.tar.gz"
      sha256 "396e6bdbadca372177a71b23a571aa692ccc56e0e43036f89a95258fce9219d1"

      def install
        bin.install "boba"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/royisme/BobaMixer/releases/download/v1.0.6/BobaMixer_linux_amd64.tar.gz"
      sha256 "37bfa6960f2a49d3023e9d0cda2e56d60b757bb0dc16b249ed592e693decd1cd"
      def install
        bin.install "boba"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/royisme/BobaMixer/releases/download/v1.0.6/BobaMixer_linux_arm64.tar.gz"
      sha256 "fafb88a6fa2048f35643ccd4033986a7263ee14bbb3fe1e7cbbc88a1d2a27965"
      def install
        bin.install "boba"
      end
    end
  end

  test do
    system "#{bin}/boba version"
  end
end
