# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Boba < Formula
  desc "CLI tool for managing multiple AI providers with intelligent routing and cost tracking"
  homepage "https://github.com/royisme/BobaMixer"
  version "1.0.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/royisme/BobaMixer/releases/download/v1.0.11/BobaMixer_darwin_amd64_v1.tar.gz"
      sha256 "573320a61f079daa56ba96ed2b121d6ff6ec558047faf9b26f42d2413ebb7b72"

      def install
        bin.install "boba"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/royisme/BobaMixer/releases/download/v1.0.11/BobaMixer_darwin_arm64_v8.0.tar.gz"
      sha256 "88f193e7bcff60a05d38e26838f4bc46c84c06177ce955a22567d321aa2f8079"

      def install
        bin.install "boba"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/royisme/BobaMixer/releases/download/v1.0.11/BobaMixer_linux_amd64_v1.tar.gz"
      sha256 "72ad341d72a4b4c5c4bba6d9e14a0395729ff69c4e951e4b28003d0090aeb67d"
      def install
        bin.install "boba"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/royisme/BobaMixer/releases/download/v1.0.11/BobaMixer_linux_arm64_v8.0.tar.gz"
      sha256 "68d8fb3ceec80c041cf5e9f41d602b2c9ca88943b338640f9c6102f72e815059"
      def install
        bin.install "boba"
      end
    end
  end

  test do
    system "#{bin}/boba version"
  end
end
