# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bobamixer < Formula
  desc "CLI tool for managing multiple AI providers with intelligent routing and cost tracking"
  homepage "https://github.com/royisme/BobaMixer"
  version "1.0.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/royisme/BobaMixer/releases/download/v1.0.10/BobaMixer_darwin_amd64.tar.gz"
      sha256 "298e733231a3e93e8c9d77c3febf6b6e63cf8d53e58d12d2e23c0d07f0065708"

      def install
        bin.install "boba"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/royisme/BobaMixer/releases/download/v1.0.10/BobaMixer_darwin_arm64.tar.gz"
      sha256 "eddf7fb236d6554714b6d06a4b5cdd2afe6387869cdfc10125201a333a7b64b4"

      def install
        bin.install "boba"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/royisme/BobaMixer/releases/download/v1.0.10/BobaMixer_linux_amd64.tar.gz"
      sha256 "45e9a0621d3d3d8313180c75cd9adac6dd885dcb156cb6b39e497da6f5e9be7b"
      def install
        bin.install "boba"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/royisme/BobaMixer/releases/download/v1.0.10/BobaMixer_linux_arm64.tar.gz"
      sha256 "ac18d54a733b3df738250b7a54bc2cce001e99dcbbbec128540c6b9b1a0e8176"
      def install
        bin.install "boba"
      end
    end
  end

  test do
    system "#{bin}/boba version"
  end
end
