# This file was generated by GoReleaser. DO NOT EDIT.
cask "bobamixer" do
  name "bobamixer"
  desc "CLI tool for managing multiple AI providers with intelligent routing and cost tracking"
  homepage "https://github.com/royisme/BobaMixer"
  version "2.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "boba"

  on_macos do
    on_intel do
      url "https://github.com/royisme/BobaMixer/releases/download/v#{version}/BobaMixer_darwin_amd64.tar.gz",
        verified: "github.com/royisme/BobaMixer"
      sha256 "090c8c6775e2fbcebf70d9b20adf96e88379f15f65158ae6263b1e50a426ae3b"
    end
    on_arm do
      url "https://github.com/royisme/BobaMixer/releases/download/v#{version}/BobaMixer_darwin_arm64.tar.gz",
        verified: "github.com/royisme/BobaMixer"
      sha256 "8de9d55a99eb3f7fff56d7cbadea89701ddf8cd508b2eb5938bddb4910e05ee2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/royisme/BobaMixer/releases/download/v#{version}/BobaMixer_linux_amd64.tar.gz",
        verified: "github.com/royisme/BobaMixer"
      sha256 "14851172c1c088838134f27667e5fa9165254167038f799dafc507aabce6b4fe"
    end
    on_arm do
      url "https://github.com/royisme/BobaMixer/releases/download/v#{version}/BobaMixer_linux_arm64.tar.gz",
        verified: "github.com/royisme/BobaMixer"
      sha256 "c3a2e63868de7e835e3732af37e97feb515ee42464d4d25154382e9c4b6a6106"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/boba"]
    end
  end

  # No zap stanza required
end
