# This file was generated by GoReleaser. DO NOT EDIT.
cask "bobamixer" do
  name "bobamixer"
  desc "CLI tool for managing multiple AI providers with intelligent routing and cost tracking"
  homepage "https://github.com/royisme/BobaMixer"
  version "2.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "boba"

  on_macos do
    on_intel do
      url "https://github.com/royisme/BobaMixer/releases/download/v#{version}/BobaMixer_darwin_amd64.tar.gz",
        verified: "github.com/royisme/BobaMixer"
      sha256 "839918e240a4fb85381de18fc87836c4b42a7a106d30a270d3247873291f3474"
    end
    on_arm do
      url "https://github.com/royisme/BobaMixer/releases/download/v#{version}/BobaMixer_darwin_arm64.tar.gz",
        verified: "github.com/royisme/BobaMixer"
      sha256 "7898f228009346dc87457cb7d0820deb6a305190bd126ea7269867f25afe5735"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/royisme/BobaMixer/releases/download/v#{version}/BobaMixer_linux_amd64.tar.gz",
        verified: "github.com/royisme/BobaMixer"
      sha256 "b36f4261ba6850888169577fde9507d4b87fdf209c42f91883b179fe7206c0ba"
    end
    on_arm do
      url "https://github.com/royisme/BobaMixer/releases/download/v#{version}/BobaMixer_linux_arm64.tar.gz",
        verified: "github.com/royisme/BobaMixer"
      sha256 "0e6596fa0a3f0cc8f71de283be24a8d6c6badc93fc4fa8685322a11a9507a8c1"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/boba"]
    end
  end

  # No zap stanza required
end
