# This file was generated by GoReleaser. DO NOT EDIT.
cask "boba" do
  name "boba"
  desc "CLI tool for managing multiple AI providers with intelligent routing and cost tracking"
  homepage ""
  version "1.0.17"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "boba"

  on_macos do
    on_intel do
      url "https://github.com/royisme/BobaMixer/releases/download/v#{version}/BobaMixer_darwin_amd64.tar.gz"
      sha256 "485c85768d9e1a1dfd8e9e13bdc18cb51acf9a3ff6160faa4fe607bf3142a9db"
    end
    on_arm do
      url "https://github.com/royisme/BobaMixer/releases/download/v#{version}/BobaMixer_darwin_arm64.tar.gz"
      sha256 "a0889ad05f63080f601a6bac01ee3ccb7338e526851b5334773ecea66f038689"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/royisme/BobaMixer/releases/download/v#{version}/BobaMixer_linux_amd64.tar.gz"
      sha256 "216dc209189d948ed21446b086666da336af9c7d3bed4dce1169e9947898d20c"
    end
    on_arm do
      url "https://github.com/royisme/BobaMixer/releases/download/v#{version}/BobaMixer_linux_arm64.tar.gz"
      sha256 "5eff436e31babff4dd44a1f1c0e0610a856a6a6bc630d4d85bb74e40eece7f14"
    end
  end

  # No zap stanza required
end
